description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - name: Install yarn
      uses: yarn/action-setup@v4
      with:
        version: 9
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
      shell: bash
  using: composite
